# Permalinks
permalink:           pretty

# Setup
title:               lex-rio personal blog
tagline:             Заметки и все подряд
url:                 http://getpoole.com
paginate:            5
baseurl:             "/"

analytics_id:        UA-130449479-1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alex Orishchuk
  url:               https://www.instagram.com/lex_rio
  email:             kushchiro@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/lex-rio/lex-rio.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
